version: "3.x"
services:
  postgres:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
  api:
    build:
      context: ./
      target: test
    depends_on:
      - postgres
    ports:
      - 8000:8000
    environment:
      APP_PORT: "8000"
      DB_HOST: postgres
      DB_PORT: "5432"
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_DATABASE_NAME: postgres
      DB_CONNECT_TIMEOUT: "10.0"
    volumes:
      - "./:/opt/project"
    command: ["pytest"]
volumes:
  postgres:
    driver_opts:
      type: tmpfs
      device: tmpfs
